export enum AdminAction {
  USER_BAN = "USER_BAN",
  USER_UNBAN = "USER_UNBAN",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  ORG_CREATED = "ORG_CREATED",
  ORG_MEMBER_REMOVED = "ORG_MEMBER_REMOVED",
  ORG_INVITE_SENT = "ORG_INVITE_SENT",
  SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
}
