export enum AuthEvent {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  MFA_SUCCESS = "MFA_SUCCESS",
  MFA_FAILED = "MFA_FAILED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
}
