export enum BillingEventType {
  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_CANCELED = "SUBSCRIPTION_CANCELED",
  PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  TRIAL_STARTED = "TRIAL_STARTED",
  TRIAL_ENDED = "TRIAL_ENDED",
  REFUND_INITIATED = "REFUND_INITIATED",
  COUPON_APPLIED = "COUPON_APPLIED",
  PLAN_SWITCHED = "PLAN_SWITCHED",
  RENEWAL = "RENEWAL",
  PROVIDER_SYNC = "PROVIDER_SYNC",
}
